# Cell type correlation

We aimed to combine the genetic expression data with the cell fraction data to investigate the correlation between the cell types with the temporal progression of brain atrophic regions in MS

In [1]:
import pandas as pd

In [42]:
# read merge_data (ID + EBM stage) for all MS patients
merged_data_All = pd.read_csv('../data/id_label/result_for_All/merged_data_All.csv')

In [43]:
merged_data_All.drop(['Unnamed: 0'], axis = 1)

,well_id,original,lobes,regions,labels,EMB_regions,NM_regions,EBM_Stage,1058685,1058682,...,1071190,1071191,1071192,1071194,1071198,1071200,1071203,1071207,1071208,1071210
0,11063,116.0,Occipital_lobe,Cun_cuneus,116.0,Cuneus,Cun_cuneus,11,3.789570,4.640806,...,2.710997,5.915190,2.728671,2.277213,7.515203,6.798809,5.330541,5.480807,5.674037,4.523316
1,11095,116.0,Occipital_lobe,Cun_cuneus,116.0,Cuneus,Cun_cuneus,11,4.400062,5.432185,...,2.080074,5.960390,3.095870,2.992298,7.693174,6.708773,5.835969,5.621881,5.681032,4.588750
2,11142,116.0,Occipital_lobe,Cun_cuneus,116.0,Cuneus,Cun_cuneus,11,4.336360,4.605071,...,2.518279,6.214643,2.696725,2.885913,7.570164,6.536117,5.208743,5.177075,5.733798,5.161416
3,126435015,116.0,Occipital_lobe,Cun_cuneus,116.0,Cuneus,Cun_cuneus,11,3.185858,4.205689,...,3.795508,7.197855,4.010861,2.538049,8.709574,7.531392,5.579490,5.807951,6.715045,4.893156
4,126435043,116.0,Occipital_lobe,Cun_cuneus,116.0,Cuneus,Cun_cuneus,11,3.982522,4.092873,...,3.532010,7.587387,4.642928,2.233732,9.671323,8.085911,5.310435,5.976924,7.557137,5.849953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,159226215,162.0,Occipital_lobe,OFuG_occipital_fusiform_gyrus,162.0,Occipital fusiform,OFuG_occipital_fusiform_gyrus,15,3.750286,4.568288,...,2.412611,8.008531,4.131020,3.941277,9.354809,8.202423,5.572959,5.599326,7.389538,3.503626
572,561,162.0,Occipital_lobe,OFuG_occipital_fusiform_gyrus,162.0,Occipital fusiform,OFuG_occipital_fusiform_gyrus,15,2.923708,4.691323,...,2.264786,9.663092,2.466259,1.726124,7.571437,10.103956,5.026006,5.122105,5.523667,5.334672
573,5168,162.0,Occipital_lobe,OFuG_occipital_fusiform_gyrus,162.0,Occipital fusiform,OFuG_occipital_fusiform_gyrus,15,3.365523,4.325862,...,3.787541,7.301706,3.281410,1.463116,8.621253,7.976418,5.598134,5.464487,6.469730,3.747490
574,5194,162.0,Occipital_lobe,OFuG_occipital_fusiform_gyrus,162.0,Occipital fusiform,OFuG_occipital_fusiform_gyrus,15,4.449756,4.524458,...,2.696085,6.389456,2.055483,4.309535,8.090273,6.917075,5.656919,5.624886,6.039179,4.407673
575,5273,162.0,Occipital_lobe,OFuG_occipital_fusiform_gyrus,162.0,Occipital fusiform,OFuG_occipital_fusiform_gyrus,15,3.502799,5.251812,...,2.523510,7.270596,1.457351,3.886024,7.335778,7.752585,5.833094,5.077064,5.492943,4.020793

In [45]:
wanted_EBM = pd.DataFrame(merged_data_All, columns=['well_id','EBM_Stage'])

In [46]:
wanted_EBM

       well_id  EBM_Stage
0        11063         11
1        11095         11
2        11142         11
3    126435015         11
4    126435043         11
..         ...        ...
571  159226215         15
572        561         15
573       5168         15
574       5194         15
575       5273         15

[576 rows x 2 columns]

In [73]:
cell_type = pd.read_csv('cell_type.csv')

In [74]:
wanted_cell = cell_type.drop(['Unknown'],axis=1)

In [78]:
wanted_cell = wanted_cell.rename(columns={'Unnamed: 0': 'well_id'}, inplace=False)

In [77]:
wanted_cell

,well_id,InNeurons,Oligodendrocytes,Endothelial,Microglia,Astrocytes,OPC,ExNeurons
0,11281,0.191315,0.144953,0.070759,0.015601,0.128590,0.010466,0.433990
1,11305,0.187380,0.123782,0.065637,0.014217,0.123149,0.009800,0.472118
2,11289,0.183228,0.092415,0.063509,0.011444,0.122182,0.006903,0.517082
3,11335,0.188124,0.109469,0.064869,0.011822,0.108081,0.007222,0.507094
4,11319,0.263540,0.040391,0.045735,0.008488,0.084148,0.005231,0.550361
...,...,...,...,...,...,...,...,...
3697,7017,0.260318,0.035714,0.053281,0.018586,0.114798,0.007072,0.506688
3698,7025,0.211033,0.142110,0.075153,0.026657,0.189148,0.009433,0.340755
3699,7033,0.368664,0.182985,0.063164,0.030714,0.200850,0.011800,0.135774
3700,7041,0.436372,0.128151,0.055599,0.027338,0.198478,0.010278,0.138581
3701,7057,0.409855,0.134809,0.062584,0.031162,0.211627,0.013189,0.130768

In [79]:
merged_cell_type = wanted_EBM.merge(wanted_cell,left_on="well_id", right_on="well_id")

In [80]:
merged_cell_type

,well_id,EBM_Stage,InNeurons,Oligodendrocytes,Endothelial,Microglia,Astrocytes,OPC,ExNeurons
0,11063,11,0.224132,0.182276,0.070206,0.014680,0.112135,0.009353,0.382933
1,11095,11,0.216551,0.207312,0.069274,0.015413,0.104115,0.009428,0.373655
2,11142,11,0.235151,0.109951,0.062310,0.011159,0.100095,0.006753,0.471526
3,126435015,11,0.253036,0.113300,0.069224,0.011358,0.113995,0.007261,0.428453
4,126435043,11,0.168457,0.167739,0.079914,0.014045,0.183128,0.012200,0.369516
...,...,...,...,...,...,...,...,...,...
571,159226215,15,0.254264,0.242658,0.062206,0.021845,0.055941,0.008493,0.350527
572,561,15,0.196582,0.040985,0.060792,0.009258,0.143931,0.007724,0.537110
573,5168,15,0.266832,0.044803,0.038803,0.010305,0.039755,0.003555,0.594155
574,5194,15,0.226348,0.217400,0.065480,0.021327,0.073237,0.006605,0.385515
575,5273,15,0.247017,0.177339,0.062317,0.020992,0.072644,0.007006,0.408888

In [137]:
merged_cell_type.columns[2:8]

Index(['InNeurons', 'Oligodendrocytes', 'Endothelial', 'Microglia',
       'Astrocytes', 'OPC'],
      dtype='object')

In [140]:
# run the correlation analysis
from scipy.stats import spearmanr
result = []
for cell in merged_cell_type.iloc[:,2:8]:
   r, p = spearmanr(merged_cell_type.EBM_Stage, merged_cell_type[cell])
   result.append([r,p])
cell_cor = pd.DataFrame(result, columns=["r","p"],
index=merged_cell_type.columns[2:8].T)
# cell_cor
cell_cor.sort_values(by='r', ascending = True)

                         r         p
Endothelial      -0.192300  0.000003
InNeurons        -0.143397  0.000557
Oligodendrocytes -0.082766  0.047091
Microglia        -0.052601  0.207467
OPC              -0.050694  0.224446
Astrocytes       -0.030578  0.463889